---
- hosts: localhost
  tasks:
    - name: kick off project sync
      uri:
        url: http://localhost/api/v1/projects/28/update/
        method: POST
        user: admin
        password: "password"
        status_code: 200
        validate_certs: False
