---
- hosts: localhost
  tasks:
    - name: kick off project sync
      uri:
        url: http://52.90.136.67/api/v1/projects/39/update/
        method: POST
        user: admin
        password: "password"
