---
- hosts: localhost
  tasks:
    - name: Create a JIRA issue
      uri:
        url: http://52.90.136.67/api/v1/projects/28/update
        method: POST
        user: "admin"
        password: "password"
        validate_certs: False
        status_code:
          - 200
          - 201
          - 202
