---
- hosts: localhost
  tasks:
    - name: kick off project sync
      uri:
        url: http://localhost/api/v1/projects/28/update/
        method: POST
        user: admin
        password: "password"
        validate_certs: false
        status_code:
          - 200
          - 201
          - 202
        
